plugins {
    id 'java'
}

group 'io.divetrip'
version '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
	implementation project(':dive-trip-library')

	// webflux
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// kafka
	implementation 'org.springframework.kafka:spring-kafka'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

tasks.named('test') {
	useJUnitPlatform()
}

test.onlyIf {
	!project.hasProperty('test')
}

springBoot {
	mainClass.set("io.divetrip.stream.DiveTripStreamApplication")
}
