spring:
  config:
    activate:
      on-profile: dev
  application:
    name: dive-trip-stream
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dive_trip?characterEncoding=UTF-8
    username: master
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumer_group01
      auto-offset-reset: earliest

spring-doc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: list
  api-docs:
    path: /api-docs
    resolveSchemaProperties: true

logging:
  level:
    root: info
    io:
      divetrip: debug
    org:
      springframework: debug
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace


